### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by ivysrono** [fohristiwhirl/sgf_to_gif#1]
Excuse me, I have tried to install golang and build your project, however, the sgf_to_gif.exe window flashes and disappears automatically.
[sgf_to_gif.exe.zip](https://github.com/fohristiwhirl/sgf_to_gif/files/1899030/sgf_to_gif.zip)

**Comment by fohristiwhirl** [comment]
In Windows you can (probably) drag an SGF file onto the app and the GIF will be automatically generated, or use the command line:

    ./sgf_to_gif.exe <filename>

**Comment by ivysrono** [comment]
Thank you very much!
