### ISSUE TITLE
the gif generated is so big

### ISSUE THREAD

**Issue by ivysrono** [fohristiwhirl/sgf_to_gif#2]
Drag https://github.com/fohristiwhirl/sgf_to_gif/blob/master/dragons.sgf to https://github.com/hex2010/sgf2gif/blob/master/bin/sgf2gif.exe 

Generated: ![dragons](https://user-images.githubusercontent.com/2649544/38621625-d1d2ba8c-3dd3-11e8-84c2-f9e2ff1002e4.gif)
183.1k

Yours, 2.37M.

**Comment by fohristiwhirl** [comment]
Hmm. There's some compression possible in the GIF format, but I'm not sure if the Go library has it available.

In the meantime, you might try sending the output through an online optimiser like this one:

https://ezgif.com/optimize

**Comment by fohristiwhirl** [comment]
I believe this is now fixed; can you try some files and tell me how the sizes seem, and whether anything seems wrong in the result? Thanks.
