### ISSUE TITLE
Add text (move numbers, coordinates, game info)

### ISSUE THREAD

**Issue by ivysrono** [fohristiwhirl/sgf_to_gif#3]
![dragons](https://user-images.githubusercontent.com/2649544/38621625-d1d2ba8c-3dd3-11e8-84c2-f9e2ff1002e4.gif)

**Comment by ivysrono** [comment]
By the way, we need these sides:
![default](https://user-images.githubusercontent.com/2649544/38623069-4fe33a8e-3dd7-11e8-96ee-2225a7d73a08.png)

**Comment by fohristiwhirl** [comment]
Not too hard if I get text working at all.

Oh as for game info, now that I think about it, writing arbitrary text (e.g. any language) is probably more work than I'll be willing to do...

**Comment by fohristiwhirl** [comment]
Coordinates are there.

Move numbers have the issue that it doubles the frames. I might not do those.

**Comment by fohristiwhirl** [comment]
OK fine, I ended up doing move numbers.
