### ISSUE TITLE
[Feature request]add opinions

### ISSUE THREAD

**Issue by ivysrono** [fohristiwhirl/sgf_to_gif#5]
There are some opinions in [hex2010/sgf2gif](https://github.com/hex2010/sgf2gif/blob/master/sgf2gif.cc):
1. Delay: the speed to display.
2. How many moves to show numbers —— I don't think this is very important, only the last is enough.
3. The cell width.
4. split has two ways:
- `*` and `number`, example: *50
- split by space, for example:
![default](https://user-images.githubusercontent.com/2649544/38623964-8ab0a186-3dd9-11e8-9f6a-70dfcd936ca8.png)
1-51:
![dragons 001-051](https://user-images.githubusercontent.com/2649544/38623988-98f9dafa-3dd9-11e8-86a9-17a97ffc4ae7.gif)
50-101:
![dragons 050-101](https://user-images.githubusercontent.com/2649544/38623990-995257de-3dd9-11e8-815d-31e10702bdcb.gif)
100-151:
![dragons 100-151](https://user-images.githubusercontent.com/2649544/38623992-99d815cc-3dd9-11e8-97f4-eef4c7f27d35.gif)
151-307:
![dragons 150-307](https://user-images.githubusercontent.com/2649544/38623993-9a3c8ec6-3dd9-11e8-9b8f-6ad82a5288f5.gif)

Thank you very much!

**Comment by fohristiwhirl** [comment]
Speed and stone width are now available via the command line.

**Comment by fohristiwhirl** [comment]
Splits are now available via command line as well, e.g.

`./sgf_to_gif.exe -t "50 100 150" filename.sgf`
