### ISSUE TITLE
[Feature request]convert all sgf files on one folder

### ISSUE THREAD

**Issue by ivysrono** [fohristiwhirl/sgf_to_gif#7]
add command line opinion:
```
sgf_to_gif.exe <foldername>
sgf_to_gif.exe -withsubfolder <foldername>
```

BTW, `32` maybe one better default config for StoneWidth, in my opinion.

**Comment by fohristiwhirl** [comment]
Done for the simple case, but I don't think I want to grapple with recursively going through sub-directories.

As for the stone size, you could compile it with that change; just change the line:

`flag.IntVar(&cfg.StoneWidth, "s", 22, "stone width")`

**Comment by ivysrono** [comment]
The most important functions have been achieved.
Thank you very much!
