### ISSUE TITLE
[feature request] Support board not 19*19

### ISSUE THREAD

**Issue by ivysrono** [fohristiwhirl/sgf_to_gif#8]
You can get tests here: https://github.com/ivysrono/sgf2gif/tree/master/tests
test-*.sgf are not 19x19.

By the way, sgf_to_gif do not support test-addition.sgf test-renju.sgf and test-shift-jis.sgf

**Comment by fohristiwhirl** [comment]
Hmm? I do support other board sizes (though not above 25, it's true). Including the one with added stones:

![add](https://user-images.githubusercontent.com/16438795/63206462-abc17100-c0ac-11e9-99cf-442e9e852d63.gif)

By the way, I see from your repo name it's a fork of a different project (theirs is sgf2gif, while I'm sgf_to_gif), is it possible you put this there?

**Comment by ivysrono** [comment]
oh, I drag the fold to sgf_to_gif.exe so this issue happen.
![图片](https://user-images.githubusercontent.com/2649544/63206902-e26cab00-c0ef-11e9-97c7-ab47cf4a3012.png)
Drag one by one, only test-27x27.sgf and test-renju.sgf does't support.

BTW, My fork store tests, there are different issue.

**Comment by fohristiwhirl** [comment]
Alright I've fixed the crash on games > 25 size.

Renju is a different game I know nothing about, so I'm unlikely to support it.

**Comment by ivysrono** [comment]
Fixed. Thanks.
https://en.wikipedia.org/wiki/Renju
We can convert renju to gif by sgf2gif.
![test-renju](https://user-images.githubusercontent.com/2649544/63208245-41d4b600-c104-11e9-850d-5845859d497a.gif)
